export enum CodigoAcaoEnum {
    PADRAO_NAO_POSSUI = 0,
    PADRAO_SUCESSO = 7,

    USUARIO_INCLUIR = 1000,
    USUARIO_ALTERAR = 1001,
    USUARIO_EXCLUIR = 1002,

    AVALIADOR_INCLUIR = 1501,
    AVALIADOR_ALTERAR = 1502,
    AVALIADOR_EXCLUIR = 1503,

    ARQUIVO_FOTO_ROSTO_INCLUIR = 1400,
    ARQUIVO_FOTO_ROSTO_ALTERAR = 1401,
    ARQUIVO_FOTO_ROSTO_EXCLUIR = 1402,
    ARQUIVO_CNPJ_CPF_INCLUIR = 1403,
    ARQUIVO_CNPJ_CPF_ALTERAR = 1404,
    ARQUIVO_CNPJ_CPF_EXCLUIR = 1405,
    ARQUIVO_IDENTIFICACAO_INCLUIR = 1406,
    ARQUIVO_IDENTIFICACAO_ALTERAR = 1407,
    ARQUIVO_IDENTIFICACAO_EXCLUIR = 1408,
    ARQUIVO_COMPROVANTE_RESIDENCIA_INCLUIR = 1409,
    ARQUIVO_COMPROVANTE_RESIDENCIA_ALTERAR = 1410,
    ARQUIVO_COMPROVANTE_RESIDENCIA_EXCLUIR = 1411,

    USUARIO_TELEFONE_INCLUIR = 1700,
    USUARIO_TELEFONE_ALTERAR = 1701,
    USUARIO_TELEFONE_EXCLUIR = 1702,

    USUARIO_DOCUMENTO_INCLUIR = 1800,
    USUARIO_DOCUMENTO_ALTERAR = 1801,
    USUARIO_DOCUMENTO_EXCLUIR = 1802
}